version: '3.3'

services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    ports:
      - "7880:7880"      # HTTP API
      - "7881:7881"      # WebRTC
      - "7882:7882/udp"  # UDP for media
      - "50000-50100:50000-50100/udp"  # Media ports range
    environment:
      LIVEKIT_KEYS: "devkey: secret"
    volumes:
      - ./livekit.yaml:/config.yaml
    command: --config /config.yaml
    restart: unless-stopped
    networks:
      - livekit-network

  # Redis for room persistence (optional but recommended)
  redis:
    image: redis:alpine
    container_name: livekit-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - livekit-network

networks:
  livekit-network:
    driver: bridge 